Fix missing prompt_key_init attribute in SwinUNETRWithPrompt
問題:
- __init__メソッドのパラメータにprompt_key_initが定義されていたが、
  self.prompt_key_initとして保存されていなかった
- _init_prompt_modules()内でself.prompt_key_initを参照した際に
  AttributeErrorが発生

修正:
- self.prompt_key_init = prompt_key_initを追加（97行目）
- これによりprompt keyの初期化方式（'uniform' or 'normal'）が
  正しく設定されるようになった

エラー解決: AttributeError: 'SwinUNETRWithPrompt' object has no attribute 'prompt_key_init'